apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: test-pr-001
  labels:
    app: test-pr-001
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: test-pr-001-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: apps/test-pr-001
