apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  labels:
    app: cart
spec:
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
      - name: cart
        image: cart
        ports:
        - containerPort: 7070
        envFrom:
        - configMapRef:
            name: cart-config
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
        readinessProbe:
          grpc:
            port: 7070
          initialDelaySeconds: 10
        livenessProbe:
          grpc:
            port: 7070
          initialDelaySeconds: 10