apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-platform-app
  labels:
    app: test-platform-app
spec:
  selector:
    matchLabels:
      app: test-platform-app
  template:
    metadata:
      labels:
        app: test-platform-app
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: test-platform-app
        image: test-platform-app
        ports:
        - name: http
          containerPort: 8080
        envFrom:
        - configMapRef:
            name: test-platform-app-config
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 300m
            memory: 256Mi
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 20
