apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-config
  namespace: cart-prod
data:
  PORT: "7070"
  REDIS_ADDR: "redis-cart.cart-prod.svc.cluster.local:6379"
  DISABLE_STATS: "0"
  DISABLE_TRACING: "0"