apiVersion: v1
kind: ConfigMap
metadata:
  name: recommendation-config
  namespace: recommendation-prod
data:
  PORT: "8080"
  PRODUCT_CATALOG_SERVICE_ADDR: "productcatalog.productcatalog-prod.svc.cluster.local:3550"
  DISABLE_STATS: "0"
  DISABLE_TRACING: "0"
  DISABLE_PROFILER: "1"