apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-config
  namespace: cart-dev
data:
  PORT: "7070"
  REDIS_ADDR: "redis-cart.cart-dev.svc.cluster.local:6379"
  DISABLE_STATS: "1"
  DISABLE_TRACING: "1"