apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cart-dev

resources:
- ../../base
- configmap.yaml
patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
  target:
    kind: Deployment
    name: cart

images:
- name: cart
  newName: ghcr.io/emmexgdc/cart
  newTag: b5dac9c

labels:
- pairs:
    environment: dev
