apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: productcatalog-dev

resources:
- ../../base
- configmap.yaml

patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
  target:
    kind: Deployment
    name: productcatalog

images:
- name: gcr.io/google-samples/microservices-demo/productcatalogservice
  newTag: v0.10.1

labels:
- pairs:
    environment: dev
  includeSelectors: false