apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: homelab-apps
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/emmexgdc/homelab-gitops
              revision: HEAD
              directories:
                - path: apps/*
                - path: apps/backstage
                  exclude: true
                - path: apps/external-secrets
                  exclude: true
                - path: apps/vault
                  exclude: true
                - path: apps/demo-api
                  exclude: true
                - path: apps/orders-api
                  exclude: true
                - path: apps/python-plat
                  exclude: true
          - list:
              elements:
                - env: dev
                - env: staging
                - env: prod
  template:
    metadata:
      name: '{{path.basename}}-{{env}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/emmexgdc/homelab-gitops
        targetRevision: HEAD
        path: apps/{{path.basename}}/overlays/{{env}}
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}-{{env}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true