apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: orders-api-dev

resources:
- ../../base
- configmap.yaml

patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
  target:
    kind: Deployment
    name: orders-api

images:
- name: orders-api
  newName: ghcr.io/emmexgdc/orders-api
  newTag: latest

labels:
- pairs:
    environment: dev
