apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: test-iuoueywq
  labels:
    app: test-iuoueywq
spec:
  selector:
    matchLabels:
      app: test-iuoueywq
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
