apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: payments-platform-api
  labels:
    app: payments-platform-api
spec:
  selector:
    matchLabels:
      app: payments-platform-api
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
