apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: frontend-staging
data:
  PORT: "8080"
  PRODUCT_CATALOG_SERVICE_ADDR: "productcatalog.productcatalog-staging.svc.cluster.local:3550"
  CART_SERVICE_ADDR: "cart.cart-staging.svc.cluster.local:7070"
  CURRENCY_SERVICE_ADDR: "currencyservice:7000"
  SHIPPING_SERVICE_ADDR: "shippingservice:50051"
  CHECKOUT_SERVICE_ADDR: "checkoutservice:5050"
  AD_SERVICE_ADDR: "adservice:9555"
  RECOMMENDATION_SERVICE_ADDR: "recommendationservice:8080"
  SHOPPING_ASSISTANT_SERVICE_ADDR: "shoppingassistantservice:8080"
  ENABLE_PROFILER: "0"
  DISABLE_TRACING: "1"
  DISABLE_STATS: "1"
  DISABLE_PROFILER: "1"
  CYMBAL_BRANDING: "false"
  FRONTEND_MESSAGE: "Staging Environment"
  ENABLE_ASSISTANT: "false"