apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: checkout-dev

resources:
- ../../base
- configmap.yaml

patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
  target:
    kind: Deployment
    name: checkout

images:
- name: checkout
  newName: ghcr.io/emmexgdc/checkout
  newTag: c52dab8

labels:
- pairs:
    environment: dev
