apiVersion: v1
kind: ConfigMap
metadata:
  name: recommendation-config
  namespace: recommendation-dev
data:
  PORT: "8080"
  PRODUCT_CATALOG_SERVICE_ADDR: "productcatalog.productcatalog-dev.svc.cluster.local:3550"
  DISABLE_STATS: "1"
  DISABLE_TRACING: "1"
  DISABLE_PROFILER: "1"