apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: payments-platform-api-dev
resources:
  - ../../base
  - configmap.yaml
  - ingress.yaml
patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: payments-platform-api
images:
  - name: payments-platform-api
    newName: emmexgdc/payments-platform-api
    newTag: latest
labels:
  - pairs:
      environment: dev
