apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice
  labels:
    app: emailservice
spec:
  selector:
    matchLabels:
      app: emailservice
  template:
    metadata:
      labels:
        app: emailservice
    spec:
      containers:
      - name: emailservice
        image: emailservice
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: emailservice-config
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
        readinessProbe:
          grpc:
            port: 8080
          initialDelaySeconds: 10
        livenessProbe:
          grpc:
            port: 8080
          initialDelaySeconds: 10