apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: productcatalog-prod

resources:
- ../../base
- configmap.yaml

patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 3
  target:
    kind: Deployment
    name: productcatalog

images:
- name: productcatalog
  newName: ghcr.io/emmexgdc/productcatalog
  newTag: 5a59e4b

labels:
- pairs:
    environment: prod
