apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-config
  namespace: backstage
data:
  app-config.production.yaml: |
    app:
      baseUrl: https://backstage.homelab.emmexgdc.uk

    backend:
      baseUrl: https://backstage.homelab.emmexgdc.uk
      listen:
        port: 7007
        host: 0.0.0.0

      auth:
        dangerouslyDisableDefaultAuthPolicy: true

      database:
        client: pg
        connection:
          host: backstage-postgres
          port: 5432
          user: ${POSTGRES_USER}
          password: ${POSTGRES_PASSWORD}
          database: ${POSTGRES_DB}

    auth:
      providers:
        guest: {}

    catalog:
      locations:
        - type: url
          target: https://github.com/emmexgdc/homelab-platform/blob/main/catalog-info.yaml
          rules:
            - allow: [Location, Template]

    kubernetes:
      serviceLocatorMethod:
        type: multiTenant

      clusterLocatorMethods:
        - type: config
          clusters:
            - name: homelab
              url: https://kubernetes.default.svc
              authProvider: serviceAccount
              skipTLSVerify: true
