apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-config
  namespace: backstage
data:
  app-config.production.yaml: |
    app:
      baseUrl: https://backstage.homelab.emmexgdc.uk

    backend:
      baseUrl: https://backstage.homelab.emmexgdc.uk
      listen:
        port: 7007
        host: 0.0.0.0

      auth:
        dangerouslyDisableDefaultAuthPolicy: true

      database:
        client: better-sqlite3
        connection: ':memory:'

    auth:
      providers:
        guest: {}

    catalog:
      locations: []

    kubernetes:
      serviceLocatorMethod:
        type: multiTenant

      clusterLocatorMethods:
        - type: config
          clusters:
            - name: homelab
              url: https://kubernetes.default.svc
              authProvider: serviceAccount
              skipTLSVerify: true
