apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cart-staging

resources:
- ../../base
- configmap.yaml

patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 0
  target:
    kind: Deployment
    name: cart

images:
- name: cart
  newName: ghcr.io/emmexgdc/cart
  newTag: aa4ca1f

labels:
- pairs:
    environment: staging
