apiVersion: v1
kind: ConfigMap
metadata:
  name: emailservice-config
  namespace: emailservice-dev
data:
  PORT: "8080"
  DISABLE_TRACING: "1"
  DISABLE_STATS: "1"
  DISABLE_PROFILER: "1"
  ENABLE_PROFILER: "0"