apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: emailservice-dev

resources:
- ../../base
- configmap.yaml

patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
  target:
    kind: Deployment
    name: emailservice

images:
- name: emailservice
  newName: ghcr.io/emmexgdc/emailservice
  newTag: latest

labels:
- pairs:
    environment: dev
  includeSelectors: false