apiVersion: apps/v1
kind: Deployment
metadata:
  name: pr-test-api
  labels:
    app: pr-test-api
spec:
  selector:
    matchLabels:
      app: pr-test-api
  template:
    metadata:
      labels:
        app: pr-test-api
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: pr-test-api
        image: pr-test-api
        ports:
        - name: http
          containerPort: 8080
        envFrom:
        - configMapRef:
            name: pr-test-api-config
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 300m
            memory: 256Mi
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 20
