apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pr-test-api
  labels:
    app: pr-test-api
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: pr-test-api-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: apps/pr-test-api
