apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyservice
  labels:
    app: currencyservice
spec:
  selector:
    matchLabels:
      app: currencyservice
  template:
    metadata:
      labels:
        app: currencyservice
    spec:
      containers:
      - name: currencyservice
        image: currencyservice
        ports:
        - containerPort: 7000
        envFrom:
        - configMapRef:
            name: currencyservice-config
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
        readinessProbe:
          grpc:
            port: 7000
          initialDelaySeconds: 10
        livenessProbe:
          grpc:
            port: 7000
          initialDelaySeconds: 10