apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: test-react
  labels:
    app: test-react
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: test-react-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: apps/test-react
