apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-pr-002
  description: test-pr-002 service
  tags:
    - kubernetes
    - gitops
spec:
  type: service
  lifecycle: production
  owner: platform
