apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: frontend-prod

resources:
- ../../base
- configmap.yaml

patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 3
  target:
    kind: Deployment
    name: frontend

images:
- name: gcr.io/google-samples/microservices-demo/frontend
  newTag: v0.10.1

labels:
- pairs:
    environment: prod
  includeSelectors: false