apiVersion: apps/v1
kind: Deployment
metadata:
  name: shippingservice
  labels:
    app: shippingservice
spec:
  selector:
    matchLabels:
      app: shippingservice
  template:
    metadata:
      labels:
        app: shippingservice
    spec:
      containers:
      - name: shippingservice
        image: shippingservice
        ports:
        - containerPort: 50051
        envFrom:
        - configMapRef:
            name: shippingservice-config
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
        readinessProbe:
          grpc:
            port: 50051
          initialDelaySeconds: 10
        livenessProbe:
          grpc:
            port: 50051
          initialDelaySeconds: 10