apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vpa-recommender
  namespace: kube-system
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: vpa-recommender
  namespaceSelector:
    matchNames:
      - kube-system
  endpoints:
    - port: metrics
      interval: 30s